language: python
os:
  - linux
env:
  global:
    - PIP_CACHE_DIR="$HOME/.cache/pip"  # unify pip cache location for all platforms
# use cache for big builds like pandas (to minimise build time).
# If issues, clear cache
# https://docs.travis-ci.com/user/caching/#Clearing-Caches
    - CODECOV_TOKEN="b5a12d8b-bcfc-476b-aca0-6f0b68410a3a"
cache:
  pip: true
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
notifications:
  email: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - python setup.py install
  - pip install pytest coverage codecov
#before_script:
script:
  - coverage run --source=prepnet -m pytest
after_script:
  - codecov
branches:
  only:
    - master
  

